name: run-tests
on:
  # Run this workflow whenever changes are pushed to any branch.
  push:
  # Add a dispatch button to run this workflow manually.
  workflow_dispatch:
    inputs:
      tags:
        description: 'Run this workflow'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m tests.tests
